;----------------------------------
; Anti Intruder 100
;----------------------------------
CSEG AT 0H
LJMP INIT
ORG 100H

; Eingabevektor
EINGANGSSIGNAL EQU 20H
A_FELD EQU EINGANGSSIGNAL.0
M_KNOPF1 EQU EINGANGSSIGNAL.2
M_KNOPF2 EQU EINGANGSSIGNAL.3
M_FELD EQU EINGANGSSIGNAL.4
SICHERHEITSKNOPF EQU EINGANGSSIGNAL.6

; Ausgabevektor
AUSGANGSSIGNAL EQU 21H
AUSEN_TUER EQU AUSGANGSSIGNAL.0
INNEN_TUER EQU AUSGANGSSIGNAL.1
ALARM EQU AUSGANGSSIGNAL.7

; Merker
ANFANGSZUSTAND EQU 22H
MERKER_TASTENFELD_AUSSEN_AN EQU 23H
MERKER_TASTENFELD_INNEN_AN EQU 24H

; INITIALISIERUNG
INIT:
MOV AUSGANGSSIGNAL, #0FDH ; Bit 1 leuchtet
MOV EINGANGSSIGNAL, #00H
MOV P1, #0FFH

;--------------------
; SCHLEIFE
;--------------------
SCHLEIFE:
	MOV EINGANGSSIGNAL, P1
	MOV P3, AUSGANGSSIGNAL
	
	
STATUS_WARTE_AUF_MITTE:
	CHECK_M_KNOPF1:
		MOV EINGANGSSIGNAL, P1
		
		MOV C, M_KNOPF1
		JNC STATUS_WARTE_AUF_MITTE_2 ; M_KNOPF1 ist gedrückt
		LJMP CHECK_M_KNOPF2
	CHECK_M_KNOPF2:
		MOV EINGANGSSIGNAL, P1
		
		MOV C, M_KNOPF2 ; wenn Knopf 2 dann JMP zu MITTE_1
		JNC STATUS_WARTE_AUF_MITTE_1 ; wenn kein Knopfdruck passiert, keine weitere Verarbeitung
		LJMP SCHLEIFE ; JA


STATUS_WARTE_AUF_MITTE_1:
	; START: Wait loop, time: 4 us
	; Clock: 12000.0 kHz (12 / MC)
	; Used registers: R0
	MOV	R0, #04h
	NOP
	DJNZ	R0, $
	NOP
	;CHECK VON KNOPF 1 IM TIMER
	; ODER ALARM

	MOV EINGANGSSIGNAL, P1
	
	MOV C, M_KNOPF1
	JNC WARTE_AUF_DRITTEN
	LJMP SCHLEIFE

STATUS_WARTE_AUF_MITTE_2:
	; START: Wait loop, time: 4 us
	; Clock: 12000.0 kHz (12 / MC)
	; Used registers: R0
	MOV	R0, #14h
	NOP
	DJNZ	R0, $
	NOP
	;CHECK VON KNOPF 2 IM TIMER
	; WEITER ZU CHECK KEYFELD
	; ODER ALARM

	MOV EINGANGSSIGNAL, P1
	
	MOV C, M_KNOPF2
	JNC WARTE_AUF_DRITTEN
	LJMP SCHLEIFE

WARTE_AUF_DRITTEN:
	; START: Wait loop, time: 4 us
	; Clock: 12000.0 kHz (12 / MC)
	; Used registers: R0
	MOV	R0, #14h
	NOP
	DJNZ	R0, $
	NOP

	MOV EINGANGSSIGNAL, P1 

	MOV C, A_FELD ; Außenfeld wird gedrückt -> außen Tür auf
	JNC AUSEN_TUER_AUF

	MOV C, M_FELD ; Vice versa
	JNC INNEN_TUER_AUF

	LJMP ALARM_EINSCHALTEN ; Nicht erfolgreich -> springe zu schleife !!! ALARM AUSLÖSEN TODO
	

ALARM_EINSCHALTEN: ; ALLE Türen zu
	MOV EINGANGSSIGNAL, P1 

	MOV C, SICHERHEITSKNOPF
	JNC ALARM_AUSSCHALTEN

	SETB AUSEN_TUER
	SETB INNEN_TUER
	CLR ALARM
	
	MOV P3, AUSGANGSSIGNAL

	LJMP ALARM_EINSCHALTEN

ALARM_AUSSCHALTEN:
	SETB AUSEN_TUER
	CLR INNEN_TUER
	SETB ALARM
	MOV P1, #0FFH

	LJMP SCHLEIFE
	
INNEN_TUER_AUF: ; Außen zu Innen auf
	SETB AUSEN_TUER
	CLR INNEN_TUER
	MOV P1, #0FFH
	LJMP SCHLEIFE
	

AUSEN_TUER_AUF: ; Außen auf Innen zu
	SETB INNEN_TUER
	CLR AUSEN_TUER
	MOV P1, #0FFH
	LJMP SCHLEIFE

;-------------------
; Ausgabe
;-------------------


; SCHLEIFENENDE
LJMP SCHLEIFE
;----------------

END
